<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-UMGIKAS2" failures="3" tests="6" name="SwagLabs Tests" time="73.283" errors="0" timestamp="2025-07-12T14:58:39 IST">
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="8.586">
    <failure type="java.lang.AssertionError" message="Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]
at testcases.InvalidLoginTest.loginWithInvalidCredentials(InvalidLoginTest.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="11.225"/>
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="11.91"/>
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="12.398">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.ValidLoginTest.loginWithMultipleUsers(ValidLoginTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- loginWithMultipleUsers -->
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="1.273"/>
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="1.466">
    <failure type="java.lang.AssertionError" message="Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]
at testcases.InvalidLoginTest.loginWithInvalidCredentials(InvalidLoginTest.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
</testsuite> <!-- SwagLabs Tests -->
